#!/usr/bin/env python3
"""Generate cores/agentos_neo_postgres/model.json from the agentos_neo_xentral core.

The postgres core speaks the SAME outward model as the Xentral facade (contract-2
schemas, entities, operations) but persists into a tenant-owned Postgres. Cores
must not import each other's content at runtime ("copy, never import"), so the
model travels as a **generated snapshot**: this script executes ``metadata()`` of
every agentos_neo_xentral adapter and writes the result as data.

Regenerate after every agentos_neo_xentral model change:

    PYTHONPATH=<agent-hub-labs>/backend python scripts/generate_neo_postgres_model.py

The snapshot is deterministic (no timestamps); ``modelVersion`` is a content
hash, so CI can regenerate and fail on drift.

Stripped from the snapshot (facade-specific, not part of the model):
  * ``verified`` / ``priority`` per-field stamps (live-test results and blue
    wishes of the *Xentral* upstream),
  * ``origin`` / ``emulation`` markers (the postgres core stamps its own),
  * actions marked as ``wish`` (declared-but-unimplemented against Xentral).
"""

from __future__ import annotations

import hashlib
import json
import sys
import types
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "cores" / "agentos_neo_postgres" / "model.json"

# Speaking-id prefix per entity for records CREATED by the postgres core.
# Aligned with the facade's vocabulary where one exists; ids are core-local
# either way (the two cores never share a data pool).
ID_PREFIXES: dict[str, str] = {
    "Quote": "quo_",
    "SalesOrder": "so_",
    "SalesInvoice": "si_",
    "DeliveryNote": "dn_",
    "CreditNote": "cn_",
    "Return": "ret_",
    "PurchaseOrder": "po_",
    "GoodsReceipt": "gr_",
    "PurchaseInvoice": "pi_",
    "Customer": "cus_",
    "Supplier": "sup_",
    "Channel": "ch_",
    "Product": "prd_",
    "PriceList": "pl_",
    "Shipment": "ship_",
    "Payment": "paym_",
    "StockMovement": "sm_",
    "StorageLocation": "loc_",
    "StockTake": "stk_",
    "PickingRun": "pick_",
    "Batch": "bat_",
    "Tag": "tag_",
}


def _register_namespace() -> None:
    """Import cores under the synthetic ``xentral_entity_cores`` package, the
    same way the backend and this repo's conftest do."""
    pkg_name = "xentral_entity_cores"
    pkg = sys.modules.get(pkg_name)
    if pkg is None:
        pkg = types.ModuleType(pkg_name)
        pkg.__package__ = pkg_name
        sys.modules[pkg_name] = pkg
    pkg.__path__ = [str(REPO / "cores")]  # type: ignore[attr-defined]


def _strip(node: Any) -> Any:
    """Drop facade-specific per-field stamps, recursively."""
    if isinstance(node, dict):
        return {k: _strip(v) for k, v in node.items() if k not in ("verified", "priority")}
    if isinstance(node, list):
        return [_strip(v) for v in node]
    return node


# Standalone semantics: the facade marks fields/entities read-only wherever
# TODAY'S Xentral API lacks a write path — a gap of that upstream, not of the
# model. With our own persistence there is no upstream feeding data in, so a
# read-only entity would stay empty forever. The snapshot therefore opens every
# entity to full CRUD and every field to create+update, EXCEPT what is
# structurally computed (identity, stamps, derived subtrees).
# Root-level identity is generated by the core; NESTED id/number leaves are
# reference payloads (orders: [{id, number}], trace.goodsReceipts …) and must
# stay writable, so this set applies at depth 0 only.
_COMPUTED_FIELDS = frozenset({"id", "number"})
# Denied at every depth: type discriminators and system stamps.
_COMPUTED_ALWAYS = frozenset({"object", "createdAt", "updatedAt"})
# Derived subtrees stay read-only (matched by key at any depth — mind that a
# nested leaf sharing a name, e.g. the boolean tracking.stock, is skipped too;
# an acceptable trade-off for keeping the rule simple).
_COMPUTED_SUBTREES = frozenset(
    {"totals", "documents", "fulfillment", "holds", "discounts", "priceSource", "cost", "stock"}
)
STANDALONE_OPERATIONS = ["list", "read", "create", "update", "delete"]


def _open_writability(props: dict[str, Any], depth: int = 0) -> None:
    """Make every non-computed field creatable+updatable, in place."""
    for name, spec in props.items():
        if not isinstance(spec, dict):
            continue
        if name in _COMPUTED_ALWAYS or name in _COMPUTED_SUBTREES:
            continue  # keep the facade's readOnly marking (and skip the subtree)
        if depth == 0 and name in _COMPUTED_FIELDS:
            continue
        sub = spec.get("properties") or (spec.get("node") or {}).get("properties")
        if isinstance(sub, dict):
            # A container inherits the facade's readOnly marking on EVERY
            # level (prices.sale, manufacturer, bom …) — clear it so the
            # opened leaves actually count as writable.
            spec.pop("access", None)
            _open_writability(sub, depth + 1)
            continue
        spec.pop("access", None)
        spec["creatable"] = True
        spec["updatable"] = True


def main() -> int:
    _register_namespace()
    from xentral_entity_cores.agentos_neo_xentral.manifest import CORE

    entities: list[dict[str, Any]] = []
    for adapter in CORE.adapters:
        meta = adapter.metadata(None)
        key = meta["key"]
        prefix = ID_PREFIXES.get(key)
        if not prefix:
            print(f"::error::no ID_PREFIX for entity {key} — add it to the generator")
            return 1
        # The postgres core stamps its own origin/emulation; wish-actions are
        # Xentral-upstream gaps, meaningless against our own persistence.
        meta.pop("origin", None)
        meta.pop("emulation", None)
        actions = [a for a in meta.get("actions") or [] if not a.get("wish")]
        if actions:
            meta["actions"] = actions
        else:
            meta.pop("actions", None)
        meta = _strip(meta)
        _open_writability(meta["rootNode"]["properties"])
        meta["operations"] = list(STANDALONE_OPERATIONS)
        entities.append(
            {
                "key": key,
                "label": adapter.manifest.label_en,
                "category": adapter.manifest.category,
                "operations": list(STANDALONE_OPERATIONS),
                "idPrefix": prefix,
                "metadata": meta,
            }
        )

    payload = {"source": "agentos_neo_xentral", "entities": entities}
    digest = hashlib.sha256(
        json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()[:12]
    payload = {"modelVersion": digest, **payload}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}: {len(entities)} entities, modelVersion={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
